// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package mycsharpdemocalc;

@net.sf.jni4net.attributes.ClrInterface
public interface ICalc {
    
    //<generated-interface>
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;)LSystem/String;")
    java.lang.String MySuperSmartFunctionIDontHaveInJava(java.lang.String filename, java.lang.String gate_name);
    //</generated-interface>
}
